# Generated by Django 4.0.4 on 2022-05-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'managed': False},
        ),
    ]
