# Generated by Django 4.0.4 on 2022-05-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0002_alter_timesheet_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timesheet',
            table='timeSheet',
        ),
    ]
