# Generated by Django 4.0.4 on 2022-06-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0005_competence'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competence',
            table='Competences',
        ),
    ]
