# Generated by Django 4.0.4 on 2022-06-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0006_alter_competence_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantCompetence',
            fields=[
                ('idCompetence', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'consultantsCompetences',
                'managed': False,
            },
        ),
    ]
