# Generated by Django 4.0.4 on 2022-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0008_formulaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('idMission', models.BigAutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('nomMission', models.TextField()),
            ],
            options={
                'db_table': 'missions',
                'managed': False,
            },
        ),
    ]
