# Generated by Django 4.0.4 on 2022-07-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0009_missions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competence',
            table='competences',
        ),
    ]
