# Generated by Django 4.0.4 on 2022-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0010_alter_competence_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionsType',
            fields=[
                ('idMissionType', models.BigAutoField(db_column='idMissionType', primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'MissionsType',
                'managed': False,
            },
        ),
    ]
