# Generated by Django 4.0.4 on 2022-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopilotDjangoApp', '0011_missionstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitesMissions',
            fields=[
                ('idActivitesMissions', models.BigAutoField(db_column='idActivitesMissions', primary_key=True, serialize=False)),
                ('tjm', models.IntegerField()),
                ('estimationCharge', models.IntegerField()),
                ('devise', models.TextField()),
                ('tauxChangeEur', models.TextField()),
            ],
            options={
                'db_table': 'activitesMissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitesType',
            fields=[
                ('idActivitesType', models.BigAutoField(db_column='idActivitesType', primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'ActivitesType',
                'managed': False,
            },
        ),
    ]
